### ISSUE TITLE
Most of the entity embeddings are arrays of zeros

### ISSUE THREAD

**Issue by ogencoglu** [kormilitzin/med7#1]
Some of the recognized entities have zero array as the vector. I couldn't think of any particular reason. Help would be appreciated.

```
text = 'Darbepoetin alfa administered Q2W safely and effectively treats anemia in hemodialysis patients without having to increase the dose, according to researchers in Portugal.'
med7 = spacy.load('en_core_med7_lg')
doc = med7(text)
for ent in doc.ents:
    print(ent, (ent.vector == 0).all())
```
results in

```
Darbepoetin alfa False
Q2W True
```
So the vector for Q2W (means _once every two weeks_) is all zeros.

**Comment by kormilitzin** [comment]
Hi @ogencoglu , thanks for reporting this. Please have a look at [a very old PR in spaCy re empty OOV vectors](https://github.com/explosion/spaCy/issues/1092). While both entities were correctly identified by the NER as such:

```
[(ent.text, ent.label_) for ent in doc.ents]

[('Darbepoetin alfa', 'DRUG'), ('Q2W', 'FREQUENCY')]

```
`Q2W` vector was indeed empty. In order to preserve POS and Tagger pipelines, the "en_core_med7_lg" was trained on "en_core_web_lg" model, but with removed NER pipeline, so the dimension of vectors is 685k unique vectors by 300 dimensions. We are currently working on improving the vector representation of OOV (by re-training on more diverse data and examples) and experimenting with a larger set of vectors.

You can mitigate this problem by introducing [new vectors](https://spacy.io/usage/vectors-similarity#custom-vectors-add) for example.

**Comment by ogencoglu** [comment]
Thanks for the quick reply! Waiting for your training updates.
