### ISSUE TITLE
med7 version compatible with Spacy3 is slower

### ISSUE THREAD

**Issue by ervivek** [kormilitzin/med7#13]
Today I tried to use the med7 version which is compatible with Spacy3. This is too slow. With the earlier version (compatible with spacy 2.3), it was processing 200k sentences in 3mins, while a version compatible with spacy 3 is processing it in 30mins. Can you please guide me, am I missing something?

**Comment by kormilitzin** [comment]
@ervivek thank you for reporting this. If you have access to GPUs, it should be faster. Make sure you use `docs = nlp.pipe(list_of_texts)` to speed up the processing. Since Med7 is similar to standard spaCy's models (e.g. `en_core_web_lg`) you can use tricks and tips provided by its developers. Have a look at their [documentation](https://spacy.io/usage/processing-pipelines#disabling) or elsewhere.

Also, note that the Transformers-based model `trf` is quite experimental and we still work on it.

**Comment by ervivek** [comment]
Hi,

Thanks for your response. I am using the docs = nlp.pipe(list_of_texts)
already. I will try to use the gpu cluster but I have noticed that my
cluster is almost unused. It seems this med7 version is not exploiting the
parallel processing capabilities.

------------------------
Vivek Gupta
Ph 9871403959
